In [1]:
#1. What is a Python library? Why do we use Python libraries?

import numpy as np 
#python libraries are collection of modules and function that can be used to perform specific task.
#Libraries are prewritten code which save time and efforts.



In [2]:
#2. What is the difference between Numpy array and List?

#memory allocation in array is contigious while in list it is random.
#In array homogenious data is used while in list hetrogenious data can be used.
#array is statically defined while lists are dynamically defined.


In [3]:
# 3. Find the shape, size and dimension of the following array?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


In [4]:
# 4. Write python code to access the first row of the following array?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]
arr[0]

array([1, 2, 3, 4])

In [5]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]
arr[2][3]

12

In [6]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [7]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?
np.random.rand(3,3)

array([[0.08929327, 0.23643426, 0.72339945],
       [0.0373616 , 0.0393355 , 0.79706627],
       [0.7010252 , 0.98617664, 0.42826084]])

In [8]:
# 8. Describe the difference between np.random.rand and np.random.randn?

#np.random.rand generate random arr of specified shape while np.random.randn generate random array of 
#shape on normal distribution curve

In [9]:
# 9. Write code to increase the dimension of the following array?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [10]:
# 10. How to transpose the following array in NumPy?

# [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]
a=np.zeros((4,3))
a+arr.T

array([[ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.],
       [ 4.,  8., 12.]])

In [11]:
# 11. Consi^er the following matrix:

# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


A2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
B2=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [12]:
A2*B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [13]:
#B2@A2 #Input operand 1 has a mismatch in its core dimension 0, 
#with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)
#matrix multiplication not possible

In [14]:
A2+B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [15]:
B2-A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
B2/A2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# 12.  Which function in Numpy can be use^ to swap the byte or^er of an array?
#np.byteswap() function .

# 13.  What is the significance of the np.linalg.inv function?
#it is used find out the inverse of the matrix.

# 14. What ^oes the np.reshape function ^o, an^ how is it use^?
#np.reshape() is used to  reshape the given array if in case all the elements are utilized to reshape it.

# 15. What is broa^casting in Numpy?
#broadcasting is concept where we can perform operations on arrays of different shape and size.